import SEO from "../components/SEO";
import PageHero from "../components/PageHero";
import { Link } from "react-router-dom";
import { FaGlobe, FaMobileAlt, FaRobot, FaShieldAlt, FaCloud, FaDatabase, FaArrowRight } from "react-icons/fa";

const showcases = [
  { Icon: FaGlobe, title: "Business web platforms", category: "Web", description: "Responsive public-facing websites and business portals with clear information architecture, strong calls to action and mobile-first UX.", tech: ["React", "Vite", "Tailwind CSS"], image: "/blog/web-development.jpg" },
  { Icon: FaMobileAlt, title: "Mobile service products", category: "Mobile", description: "Cross-platform application experiences designed around simple flows, reliable data and practical day-to-day use.", tech: ["Flutter", "Dart", "Firebase"], image: "/blog/flutter.jpg" },
  { Icon: FaRobot, title: "AI-assisted workflows", category: "AI", description: "Automation concepts that connect people, data and intelligent tools to reduce repetitive work and improve response time.", tech: ["AI", "Automation", "APIs"], image: "/blog/ai.jpg" },
  { Icon: FaShieldAlt, title: "Security improvement", category: "Security", description: "Practical cybersecurity engagements focused on identifying exposure, improving controls and building safer digital habits.", tech: ["Risk review", "Security", "Awareness"], image: "/blog/cybersecurity.jpg" },
  { Icon: FaCloud, title: "Cloud deployment", category: "Cloud", description: "Deployment and hosting patterns that make digital products easier to operate, back up and scale.", tech: ["Hosting", "CI/CD", "Backups"], image: "/hero.png" },
  { Icon: FaDatabase, title: "Business data systems", category: "Software", description: "Structured systems for managing records, workflows and operational information with room for future integrations.", tech: ["Databases", "APIs", "Dashboards"], image: "/logo.png" },
];

function Portfolio() {
  return <>
    <SEO title="Portfolio | SeeFuture Tech Hub" description="Explore representative SeeFuture Tech Hub solution showcases across web, mobile, AI, cybersecurity, cloud and business software." keywords="SeeFuture Tech Hub portfolio, web projects, mobile apps, AI, cybersecurity, software" />
    <PageHero eyebrow="Selected solution showcases" title="Work that shows what we can build." description="A visual overview of the types of digital products and technology engagements SeeFuture Tech Hub can deliver. Client-approved screenshots can be added here as projects go live." action="Discuss your project" />

    <section className="sf-section bg-slate-50"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mb-12 max-w-3xl"><span className="sf-eyebrow">Portfolio</span><h2 className="mt-5 text-3xl font-black md:text-5xl">Representative solution patterns.</h2><p className="mt-5 leading-8 text-slate-600">We avoid inventing client results or screenshots. These showcases communicate our capabilities and can be replaced with approved project case studies as they become available.</p></div><div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{showcases.map(({Icon,title,category,description,tech,image})=><article key={title} className="sf-card overflow-hidden"><div className="relative h-52 overflow-hidden bg-slate-950"><img src={image} alt="" className="h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/20 to-transparent"/><div className="absolute bottom-4 left-5 flex items-center gap-3 text-white"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 backdrop-blur"><Icon/></span><span className="text-xs font-black uppercase tracking-[.18em]">{category}</span></div></div><div className="p-7"><h3 className="text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-slate-600">{description}</p><div className="mt-5 flex flex-wrap gap-2">{tech.map(t=><span key={t} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{t}</span>)}</div><Link to="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-blue-600">Build something similar <FaArrowRight size={11}/></Link></div></article>)}</div></div></section>

    <section className="sf-section bg-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><span className="sf-eyebrow">Case-study ready</span><h2 className="mt-5 text-3xl font-black md:text-5xl">Turn your project into the next showcase.</h2><p className="mt-5 max-w-2xl leading-8 text-slate-600">For completed client work, we can present the challenge, solution, technology stack, screenshots and measurable outcomes in a clean case-study format.</p></div><div className="rounded-3xl bg-slate-950 p-8 text-white"><p className="text-sm font-bold text-cyan-300">CASE STUDY FORMAT</p><div className="mt-6 grid gap-4 text-sm">{["Challenge", "Solution", "Technology", "Screenshots", "Outcome"].map(x=><div key={x} className="flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-cyan-300"/>{x}</div>)}</div></div></div></div></section>
  </>;
}
export default Portfolio;
